# --------------------------------
# Integration test for run-java.sh
# --------------------------------

job_defaults: &job_defaults
  environment:
    JDK8_TAG: 8u151
    JDK9_TAG: 9.0.1-11
  
jobs:
  # Create the Docker image used for running the tests
  # Two versions for Java 8 and Java 9
  build_runner_image_8:
    <<: *job_defaults
    
    docker:
     - image: docker:17.09.0-ce-git

    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
          
      - run:
          name: Create and push builder image for Java 8
          working_directory: ${CIRCLE_WORKING_DIRECTORY}/test/docker
          command: |
            docker build --build-arg JDK=${JDK8_TAG} -t fabric8io/run-java-sh-test:${JDK8_TAG}
            docker push fabric8io/run-java-sh-test:${JDK8_TAG}
            docker tag fabric8io/run-java-sh-test:${JDK8_TAG} fabric8io/run-java-sh-test:openjdk8
            docker push fabric8io/run-java-sh-test:openjdk8
            docker tag fabric8io/run-java-sh-test:${JDK8_TAG} fabric8io/run-java-sh-test:latest
            docker push fabric8io/run-java-sh-test:latest

  build_runner_image_9:
    docker:
      - image: docker:17.09.0-ce-git

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.09.0-ce

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
          
      - run:
          name: Create and push builder image for Java 9
          working_directory: ${CIRCLE_WORKING_DIRECTORY}/test/docker
          command: |
            docker build --build-arg JDK=${JDK9_TAG} -t fabric8io/run-java-sh-test:${JDK9_TAG}
            docker push fabric8io/run-java-sh-test:${JDK9_TAG}
            docker tag fabric8io/run-java-sh-test:${JDK9_TAG} fabric8io/run-java-sh-test:openjdk9
            docker push fabric8io/run-java-sh-test:openjdk9
            
  # Run the integration test
  # Parameterized with the Java version
  test_8:
    docker:
      - image: fabric8io/run-java-sh-test:${JDK8_TAG}

    steps:
      - checkout
             
      - run:
          name: Run tests for JDK 8
          environment:
            RUN_JAVA_DIR: ${CIRCLE_WORKING_DIRECTORY}
            REPORT_DIR: ${CIRCLE_WORKING_DIRECTORY}/reports/jdk8
          command: bash /opt/run_tests.sh

      - store_artifacts:
          path: ${CIRCLE_WORKING_DIRECTORY}/reports/jdk8
          destination: jdk8

  test_9:
    docker:
      - image: fabric8io/run-java-sh-test:${JDK9_TAG}

    steps:
      - checkout
             
      - run:
          name: Run tests for JDK 9
          environment:
            RUN_JAVA_DIR: ${CIRCLE_WORKING_DIRECTORY}
            REPORT_DIR: ${CIRCLE_WORKING_DIRECTORY}/reports/jdk9
          command: bash /opt/run_tests.sh

      - store_artifacts:
          path: ${CIRCLE_WORKING_DIRECTORY}/reports/jdk9
          destination: jdk9
          
# =======================================================
# Workflow for running all tests
workflows:
  version: 2
  run_tests:
    jobs:
      - build_runner_image_8:
          filters:
            tags:
              only:
                /v[0-9]+(\.[0-9]+)*/
      - build_runner_image_9:
          filters:
            tags:
              only:
                /v[0-9]+(\.[0-9]+)*/
      - test_8:
          requires:
            - build_runner_image_8
          filters:
            tags:
              only:
                /v[0-9]+(\.[0-9]+)*/
      - test_9:
          requires:
            - build_runner_image_9
          filters:
            tags:
              only:
                /v[0-9]+(\.[0-9]+)*/
      
